apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test2
  name: test2
spec:
  containers:
  - image: nginx
    name: web
    ports:
      - containerPort: 8080
  - image: nginx
    name: app
    ports:
      - containerPort: 8081
  - image: nginx
    name: db
    ports:
      - containerPort: 8082
